spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql username
    password: mysql password
    url: mysql url
server:
  tomcat:
    uri-encoding: UTF-8
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 80
    height: 80
  tracker-list:
    - FastDFS Url:port
